### ISSUE TITLE
Header And Footter with RecyclerView-ListAdapter 

### ISSUE THREAD

**Issue by aike1202** [akexorcist/RecyclerView-ListAdapter#1]
I have tried to override getItemCount  like this 1. `override fun getItemCount(): Int {
        return super.getItemCount()+2
    }`
2.` override fun getItemCount(): Int {
        return currentList.size+2
    }`
Still not working 
Any advice?

**Comment by aike1202** [comment]
> I have tried to override getItemCount like this 1. `override fun getItemCount(): Int { return super.getItemCount()+2 }`
> 2.` override fun getItemCount(): Int { return currentList.size+2 }`
> Any advice?
> Still not working



> I have tried to override getItemCount like this 1. `override fun getItemCount(): Int { return super.getItemCount()+2 }`
> 2.` override fun getItemCount(): Int { return currentList.size+2 }`
> Any advice?
> Still not working

**Comment by aike1202** [comment]
> > I have tried to override getItemCount like this 1. `override fun getItemCount(): Int { return super.getItemCount()+2 }`
> > 2.` override fun getItemCount(): Int { return currentList.size+2 }`
> > Any advice?
> > Still not working
> 
> > I have tried to override getItemCount like this 1. `override fun getItemCount(): Int { return super.getItemCount()+2 }`
> > 2.` override fun getItemCount(): Int { return currentList.size+2 }`
> > Any advice?
> > Still not working

I just think of add type to my list ，any better sulution

**Comment by akexorcist** [comment]
Yes, that's best solution to make the data in RecyclerView's adapter most flatten. Keep the complex calculation to presentation layer like activity or fragment, not in adapter
